inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
  SupportedStyles:
    # The `braces` style enforces braces around all method parameters that are
    # hashes.
    - braces
    # The `no_braces` style checks that the last parameter doesn't have braces
    # around it.
    - no_braces
    # The `context_dependent` style checks that the last parameter doesn't have
    # braces around it, but requires braces if the second to last parameter is
    # also a hash literal.
    - context_dependent

# Don't quite know how to fix this, so ignore it for now
Lint/UriEscapeUnescape:
  Enabled: false

# Mongoid, not ActiveRecord, makes RuboCop's suggestions for the
# following two cops not pass tests.
Rails/FindBy:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false
